theme: jekyll-theme-cayman
title: Spotify Title
description: Spotify Description
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
    show_downloads: true
