title: Songspotters: Content Recommendation Using Spotify's Million Playlist Data Set
description: Apaar Bansal, Jacob Kohn, Alan Sage
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
