title: "Songspotters"
description: "Content Recommendation Using Spotify's Million Playlist Data Set | Apaar Bansal, Jacob Kohn, Alan Sage"                            Apaar Bansal, Jacob Kohn, Alan Sage, TF: Yujiao Chen"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
